#!/usr/bin/env python3
"""Lift the real capability data out of the Swift sources into the prototype.

WHY THIS EXISTS, and why the prototype is not hand-authored.

The whole claim the CLI onboarding makes is arithmetic: "a permission is only ever
requested because a feature you picked needs it". A prototype with invented feature
requirements cannot prove that claim, it can only illustrate it, and an illustration that
disagrees with the app is worse than no prototype because it teaches the wrong flow to
everybody who reviews it.

So the numbers in the prototype ARE the app's numbers. This script parses:

  Sources/Grux/Onboarding/SetupContract.swift    the 43 capability ids and their copy
  Sources/Grux/Onboarding/FeatureRegistry.swift  the 39 features and what each needs
  Sources/Grux/Onboarding/CapabilityRequest.swift the permission order onboarding uses
  Sources/Grux/DesignSystem/SidebarModel.swift   the 5 groups and 35 tabs

and writes the result into cli-onboarding.html between two markers, so the prototype
stays a single file that opens from a double click with no server and no build step.

Run it after any change to those four files. It is also the drift check: --check exits 1
when the embedded data no longer matches the sources, which is the failure that would
otherwise sit silently until somebody reviewed a flow the app does not have.
"""
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent

# --src exists for one recurring job: measuring a BRANCH before merging it. The prototype's
# numbers are the app's numbers, so a branch that edits FeatureRegistry.swift moves them,
# and the useful question is by how much rather than whether. Point this at a tree exported
# from any ref and --check tells you what the merge will do to the flow.
#
#   mkdir -p /tmp/w2 && git archive <ref> Grux-Mac/Sources/Grux | tar -x -C /tmp/w2
#   python3 prototypes/extract-registry.py --src /tmp/w2/Grux-Mac/Sources/Grux --check
def _src():
    if "--src" in sys.argv:
        return pathlib.Path(sys.argv[sys.argv.index("--src") + 1]).resolve()
    return HERE.parent / "Sources" / "Grux"

SRC = _src()
BLUEPRINTS = SRC.parent.parent / "docs" / "blueprints"
# --out completes the branch-measurement workflow: render a SECOND copy of the prototype
# carrying another ref's data, so the two can be opened side by side and both self tested.
# Without it, measuring a branch means editing the committed file and remembering to undo it.
def _out():
    if "--out" in sys.argv:
        return pathlib.Path(sys.argv[sys.argv.index("--out") + 1]).resolve()
    return HERE / "cli-onboarding.html"

OUT = _out()
BEGIN = "/* REGISTRY:BEGIN generated by extract-registry.py, do not edit by hand */"
END = "/* REGISTRY:END */"


def read(rel):
    p = SRC / rel
    if not p.is_file():
        sys.exit("missing source: %s" % p)
    return p.read_text(encoding="utf-8")


def strip_line_comments(text):
    """Drop whole-line // comments only.

    Deliberately not a general comment stripper. An inline // inside a Swift string
    literal is a real possibility and removing it would corrupt the copy this script
    exists to carry across verbatim.
    """
    return "\n".join(l for l in text.split("\n") if not l.strip().startswith("//"))


def swift_string(raw):
    """Unescape one Swift string literal body."""
    return raw.replace('\\"', '"').replace("\\n", "\n").replace("\\\\", "\\")


def property_map(text, prop, names):
    """Parse `var <prop>: String { switch self { case .a, .b: return "x" ... } }`.

    Returns swiftName -> string. Handles the single line form, the wrapped form where
    the return sits on the next line, and a shared case list. A `default:` arm fills in
    every name the explicit arms did not cover, which is how the contract carries the
    empty-by-default properties (`why`, `instructions`) without listing 30 blanks.
    """
    m = re.search(r"var %s: String \{\n(.*?)\n    \}\n" % re.escape(prop), text, re.S)
    if not m:
        sys.exit("could not find `var %s` in SetupContract.swift" % prop)
    body = strip_line_comments(m.group(1))
    out = {}
    default = None
    # Each arm: a case list (or `default`) followed by the first return literal after it.
    for arm in re.finditer(
        r"(?:case ((?:\.\w+(?:,\s*)?)+)|(default))\s*:\s*(?:\n\s*)?return\s+\"((?:[^\"\\]|\\.)*)\"",
        body,
    ):
        value = swift_string(arm.group(3))
        if arm.group(2):
            default = value
            continue
        for case in re.findall(r"\.(\w+)", arm.group(1)):
            out[case] = value
    if default is not None:
        for n in names:
            out.setdefault(n, default)
    missing = [n for n in names if n not in out]
    if missing and default is None:
        sys.exit("`%s` has no value for %d id(s): %s" % (prop, len(missing), ", ".join(missing)))
    return out


def build():
    contract = read("Onboarding/SetupContract.swift")
    registry = read("Onboarding/FeatureRegistry.swift")
    request = read("Onboarding/CapabilityRequest.swift")
    sidebar = read("DesignSystem/SidebarModel.swift")

    # ---- capability ids -------------------------------------------------------------
    enum_body = contract.split("enum SetupRequirement", 1)[1]
    pairs = re.findall(r'case (\w+) = "([a-z_.]+)"', enum_body)
    if not pairs:
        sys.exit("no capability ids found in SetupContract.swift")
    names = [n for n, _ in pairs]

    labels = property_map(contract, "label", names)
    remediations = property_map(contract, "remediation", names)
    whys = property_map(contract, "why", names)

    caps = {}
    for swift_name, cap_id in pairs:
        caps[cap_id] = {
            "swift": swift_name,
            "id": cap_id,
            "kind": cap_id.split(".")[0],
            "label": labels[swift_name],
            "remediation": remediations[swift_name],
            "why": whys.get(swift_name, ""),
        }

    by_swift = {n: i for n, i in pairs}

    def ids(listing):
        return [by_swift[c] for c in re.findall(r"\.(\w+)", listing) if c in by_swift]

    # ---- features -------------------------------------------------------------------
    rows_block = registry.split("static let rows: [FeatureRow] = [", 1)[1]
    rows_block = strip_line_comments(rows_block)
    features = []
    # `anyOf:` is OPTIONAL and trails the four lists. Matching it loosely is deliberate.
    #
    # THE BUG THIS SHAPE EXISTS TO PREVENT, and it already happened once. The first version
    # of this regex required the row to end at `optionalSteps: [...])`. When `anyOf` was
    # added on a branch, every row carrying one simply failed to match and was DROPPED, so
    # the parse came back with 38 features instead of 39 and reported that the branch had
    # deleted Chat. It had not. A parser that silently drops what it does not understand is
    # worse than one that crashes, so the count is asserted against the declaration count
    # below rather than trusted.
    for m in re.finditer(
        r'FeatureRow\(id: "([^"]+)", label: "([^"]+)", tier: \.(\w+),\s*'
        r"requires: \[([^\]]*)\],\s*"
        r"optional: \[([^\]]*)\],\s*"
        r"steps: \[([^\]]*)\],\s*"
        r"optionalSteps: \[([^\]]*)\]"
        r"(?:,\s*anyOf: \[(.*?)\]\s*)?\)",
        rows_block,
        re.S,
    ):
        groups = []
        for g in re.finditer(r"CapabilityGroup\(capabilities: \[([^\]]*)\], min: (\d+)\)",
                             m.group(8) or ""):
            groups.append({"capabilities": ids(g.group(1)), "min": int(g.group(2))})
        features.append({
            "id": m.group(1),
            "label": m.group(2),
            "tier": m.group(3),
            "requires": ids(m.group(4)),
            "optional": ids(m.group(5)),
            "steps": ids(m.group(6)),
            "optionalSteps": ids(m.group(7)),
            "anyOf": groups,
        })
    if not features:
        sys.exit("no FeatureRow entries parsed. The declaration shape changed.")

    # A dropped row is the failure mode that looks like a clean result, so count the
    # declarations independently of the parse and refuse to write a partial registry.
    declared = len(re.findall(r"FeatureRow\(id: ", rows_block))
    if declared != len(features):
        sys.exit("parsed %d FeatureRow entries but %d are declared. %d row(s) did not match, "
                 "which would silently ship a registry missing features. Fix the pattern."
                 % (len(features), declared, declared - len(features)))

    aliases = dict(re.findall(r'"(\w+)": "([\w.]+)"', registry.split("tabAliases", 1)[1].split("]", 1)[0]))

    # ---- blueprints -----------------------------------------------------------------
    # A BLUEPRINT DECLARES CAPABILITIES TOO, and missing that produced a wrong finding.
    #
    # This script first reported 10 capability ids as claimed by nothing. Eight of them
    # were claimed all along, by blueprints rather than by sidebar features: a blueprint is
    # a unit that requires capabilities in its own right, so `pr-digest` needs a GitHub
    # token and a repo list while the generic `schedules` feature that hosts it needs
    # neither. Counting only FeatureRegistry rows called eight live capabilities dead.
    #
    # Scanned NARROWLY, only the rows of the "Capabilities required" table. Scanning a
    # whole document for id mentions is what lets a sentence saying an id was REMOVED count
    # as that id being used, which is exactly the hole that leaves the last two invisible
    # to scripts/check-contract.py.
    blueprints = []
    if BLUEPRINTS.is_dir():
        for f in sorted(BLUEPRINTS.glob("*.md")):
            if f.name == "index.md":
                continue  # a catalogue of the others, not a declarer in its own right
            text = f.read_text(encoding="utf-8")
            if "## Capabilities required" not in text:
                continue
            table = text.split("## Capabilities required", 1)[1].split("\n## ", 1)[0]
            # NAMED bp_caps, not caps. The first version of this loop called it `caps` and
            # shadowed the capability dictionary built above, so the emitted registry
            # carried 4 capabilities instead of 43 and every count downstream was wrong.
            # It was caught only because the write line prints the number.
            bp_caps = []
            for row in re.finditer(r"^\|\s*`([a-z_.]+)`\s*\|\s*(\w+)\s*\|\s*(\w+)\s*\|",
                                   table, re.M):
                bp_caps.append({"id": row.group(1), "required": row.group(3) == "required"})
            if bp_caps:
                blueprints.append({"id": f.stem, "capabilities": bp_caps})

    # ---- sidebar groups -------------------------------------------------------------
    groups = []
    for g in re.finditer(
        r'SidebarGroupDef\(id: "(\w+)", title: "([^"]+)", items: \[(.*?)\]\)',
        sidebar,
        re.S,
    ):
        keys = re.findall(r'SidebarItem\(key: "(\w+)"', g.group(3))
        groups.append({"id": g.group(1), "title": g.group(2), "keys": keys})
    if not groups:
        sys.exit("no sidebar groups parsed")

    # ---- the permission order onboarding uses today ---------------------------------
    order_block = request.split("static let onboardingOrder: [SetupRequirement] = [", 1)[1].split("]", 1)[0]
    order = ids(order_block)

    # A LATE GUARD, because the failure it catches is silent. Everything above can parse
    # correctly and a later block can still overwrite `caps` by naming a local the same
    # thing, which is exactly what happened. Comparing the emitted set against the enum
    # parse turns that into a crash instead of a registry that is quietly 39 ids short.
    if len(caps) != len(pairs):
        sys.exit("emitting %d capabilities but SetupContract declares %d. Something "
                 "overwrote the capability map after it was built." % (len(caps), len(pairs)))

    data = {
        "generatedFrom": "Grux-Mac/Sources/Grux, parsed by prototypes/extract-registry.py",
        "capabilities": caps,
        "features": features,
        "tabAliases": aliases,
        "sidebarGroups": groups,
        "permissionOrder": order,
        "blueprints": blueprints,
        "counts": {
            "capabilities": len(caps),
            "features": len(features),
            "core": sum(1 for f in features if f["tier"] == "core"),
            "labs": sum(1 for f in features if f["tier"] == "labs"),
            "tabs": sum(len(g["keys"]) for g in groups),
            "blueprints": len(blueprints),
        },
    }
    return data


def main():
    data = build()
    payload = BEGIN + "\nconst REGISTRY = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n" + END

    template = OUT if OUT.is_file() else HERE / "cli-onboarding.html"
    if not template.is_file():
        sys.exit("%s does not exist yet. Create it with the two markers in place." % template)
    html = template.read_text(encoding="utf-8")
    if BEGIN not in html or END not in html:
        sys.exit("markers missing from %s" % OUT)
    start = html.index(BEGIN)
    stop = html.index(END) + len(END)
    updated = html[:start] + payload + html[stop:]

    if "--check" in sys.argv:
        if updated != html:
            print("DRIFT: the embedded registry no longer matches the Swift sources.")
            print("Run: python3 prototypes/extract-registry.py")
            return 1
        print("OK embedded registry matches the sources: %d capabilities, %d features "
              "(%d core, %d labs), %d tabs, %d blueprints"
              % (data["counts"]["capabilities"], data["counts"]["features"],
                 data["counts"]["core"], data["counts"]["labs"], data["counts"]["tabs"],
                 data["counts"]["blueprints"]))
        return 0

    OUT.write_text(updated, encoding="utf-8")
    c = data["counts"]
    print("wrote %d capabilities, %d features (%d core, %d labs), %d tabs, %d blueprints, "
          "%d permissions in onboarding order into %s"
          % (c["capabilities"], c["features"], c["core"], c["labs"], c["tabs"],
             c["blueprints"], len(data["permissionOrder"]), OUT.name))
    return 0


if __name__ == "__main__":
    sys.exit(main())
