import Foundation
import CryptoKit

// Canonical archival daily log artifact. One per 6am-anchored workday window.
// Assembled from Focus events, Terminal Focus (Claude Code JSONLs), chat,
// ambient transcripts (via hourly summaries), and git history.
//
// Persisted as JSON locally and mirrored as Markdown in iCloud for reading
// anywhere. See docs/superpowers/specs/2026-04-23-workday-log-design.md.

struct WorkdayLog: Codable, Identifiable, Equatable {
    // Deterministic UUID derived from dayKey so re-rollups overwrite rather
    // than duplicate. Stable across runs.
    let id: UUID
    let dayKey: String          // "2026-04-22" - 6am anchor date
    let windowStart: Date       // 06:00:00 local of dayKey
    let windowEnd: Date         // 05:59:59 local of dayKey+1 (display only)
    let generatedAt: Date
    let schemaVersion: Int

    var completedTasks: [LoggedTask]
    var codeShipped: [CodeShipment]
    var conversations: [ConversationSummary]
    var commitments: CommitmentsBreakdown
    var focusStats: FocusStats
    var insights: [String]
    // Calendar events that fell inside the workday window, correlated to
    // ambient session IDs where overlap was detected. Optional in the codable
    // layer so older logs on disk decode cleanly without a migration.
    var meetingsAttended: [LoggedMeeting]? = nil
    // Short TL;DR paragraph rendered at the top of each report. Generated by
    // the same LLM call that produces `narrative`. Distinct purpose: this is
    // 60-100 words scannable, narrative is the 200-400 word deeper read.
    var executiveSummary: String? = nil
    // Total minutes per app-category bucket (IDE, Browser, Terminal, Comms,
    // Design, Docs, Music, Other). Derived from focusStats.perAppMinutes via
    // categorizeApp() at build time. Persisted so the renderer doesn't need
    // to re-categorize on every read.
    var appCategoryMinutes: [String: Int]? = nil
    // Higher-level activity-mix bucket designed for "where did the day go"
    // bars. Combines app-category minutes with meeting durations.
    var timeAllocation: TimeAllocationBreakdown? = nil
    // Per-project foreground minutes inferred from ScreenTimeWatcher window
    // titles matched against KnownProjects.displayNames(). Replaces the
    // historically-empty focusStats.perProjectMinutes for the bar renderer.
    var projectMinutesScreentime: [String: Int]? = nil

    var narrative: String
    var tags: [String]
    var totalProductiveMinutes: Int

    static let currentSchemaVersion = 1

    // SHA-1 of dayKey → first 16 bytes → UUID. Pure; deterministic.
    static func deterministicID(forDayKey dayKey: String) -> UUID {
        let digest = Insecure.SHA1.hash(data: Data(dayKey.utf8))
        let bytes = Array(digest.prefix(16))
        let tuple: uuid_t = (
            bytes[0],  bytes[1],  bytes[2],  bytes[3],
            bytes[4],  bytes[5],  bytes[6],  bytes[7],
            bytes[8],  bytes[9],  bytes[10], bytes[11],
            bytes[12], bytes[13], bytes[14], bytes[15]
        )
        return UUID(uuid: tuple)
    }
}

// Activity-mix breakdown for the daily "where did time go" bars. Each field
// is a whole-minute count; sum may slightly exceed the workday duration
// because meeting minutes can overlap with app-foreground minutes (e.g. Zoom
// is the foreground app during a meeting).
struct TimeAllocationBreakdown: Codable, Equatable {
    var codingMinutes: Int = 0
    var terminalMinutes: Int = 0
    var browsingMinutes: Int = 0
    var commsMinutes: Int = 0
    var meetingsMinutes: Int = 0
    var designMinutes: Int = 0
    var docsMinutes: Int = 0
    var musicMinutes: Int = 0
    var otherMinutes: Int = 0
}

struct LoggedMeeting: Codable, Equatable, Hashable {
    let tsStart: Date
    let tsEnd: Date
    let eventTitle: String
    let calendarName: String
    // Set when an ambient transcript session overlapped the meeting window.
    // nil means the meeting was on the calendar but ambient wasn't capturing
    // (Mac asleep, ambient disabled, mic muted, or the user was off-device).
    let ambientSessionId: String?
}

struct LoggedTask: Codable, Equatable, Hashable {
    let title: String
    let project: String
    let completedAt: Date
    let source: String          // "chat" | "voice" | "manual"
}

struct CodeShipment: Codable, Equatable {
    let project: String         // cwd basename / repo name
    let gitBranch: String?
    var commits: [LoggedCommit]
    var claudeSessions: [LoggedClaudeSession]
}

struct LoggedCommit: Codable, Equatable, Hashable {
    let sha: String             // full 40-char
    let message: String         // first line only
    let timestamp: Date
    let filesChanged: Int
    let insertions: Int
    let deletions: Int
}

struct LoggedClaudeSession: Codable, Equatable, Hashable {
    let sessionId: String
    let cwd: String
    let turns: Int
    let totalCost: Double
    let totalTokens: Int
    var outcomeSummary: String  // Claude-generated, 1 sentence
}

struct ConversationSummary: Codable, Equatable, Hashable {
    let timestamp: Date
    let source: ConvSource
    let durationMinutes: Int
    var summary: String
    var topics: [String]
}

enum ConvSource: String, Codable, Equatable, Hashable {
    case chat
    case ambient
}

struct CommitmentsBreakdown: Codable, Equatable {
    var made: [String]
    var kept: [String]
    var stillOpen: [String]
}

struct FocusStats: Codable, Equatable {
    var onTaskMinutes: Int
    var driftingMinutes: Int
    var offTaskMinutes: Int
    var perAppMinutes: [String: Int]
    var perProjectMinutes: [String: Int]
    // Minutes the Mac was asleep inside the window, derived from
    // SleepWatcher's NDJSON. Subtracted from drift/off-task intervals so a
    // long suspended period doesn't read as "drifting".
    var systemSleptMinutes: Int = 0
}

// Index entry for the browser list - derived from WorkdayLog on save.
struct WorkdayLogIndexEntry: Codable, Identifiable, Equatable {
    let dayKey: String
    let generatedAt: Date
    let tags: [String]
    let narrativeSnippet: String   // first ~140 chars of narrative
    let totalProductiveMinutes: Int
    var id: String { dayKey }
}

// Notification fired after a log is saved (main thread). UI refreshes.
extension Notification.Name {
    static let gruxWorkdayLogSaved = Notification.Name("gruxWorkdayLogSaved")
}
